### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fecton** [fomgleb/VS.WallpapersSlideshower#3]
Could you add a native release for Linux? I tested it on Linux by wine that it doesn't work.

### Here is the screenshot:

![image](https://user-images.githubusercontent.com/76391547/183497508-6d89e55a-79fb-4037-8e94-92afdfe6d4f9.png)

**Comment by fomgleb** [comment]
Oh, you oppened this issue 26 days ago but I noticed this only now, sorry. I’m afraid I can’t do it because linux wallpapers system is different from windows. And I need to rewrite some code... (короче мне лень).
